source 'https://rubygems.org'

gem 'rails', '~> 5.1.5'
gem 'rails-api'
gem 'pg'
gem 'rails_12factor'
gem 'spring', 								:group => :development
gem 'bcrypt'
gem 'faker'
gem 'carrierwave'
gem 'mini_magick'
gem 'fog'
gem 'kaminari'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'bootstrap-sass'
gem 'slim-rails'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'rails-html-sanitizer'
gem 'sdoc',                 	'0.4.0', group: :doc
gem 'unicorn'