source 'https://rubygems.org'


gem 'rails', '4.2.0.beta4'
gem 'rails-api'
gem 'pg',             '0.17.1'
gem 'rails_12factor', '0.0.2'
gem 'spring', 								:group => :development
gem 'bcrypt'
gem 'faker'
gem 'carrierwave'
gem 'mini_magick'
gem 'fog'
gem 'kaminari'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'bootstrap-sass',       	'3.2.0.0'
gem 'slim-rails'
gem 'sass-rails',           	'5.0.0.beta1'
gem 'uglifier',             	'2.5.3'
gem 'coffee-rails',         	'4.0.1'
gem 'jquery-rails',         	'3.1.2'
gem 'turbolinks',           	'2.3.0'
gem 'jbuilder',             	'2.1.3'
gem 'rails-html-sanitizer', 	'1.0.1'
gem 'sdoc',                 	'0.4.0', group: :doc
gem 'unicorn'