development:
  adapter: postgresql
  database: todo_development
  encoding: utf8
  host: localhost
  password:
  pool: 5
  username: postgres
  port: 5432

test: &test
  adapter: postgresql
  database: todo_test
  encoding: utf8
  host: localhost
  password:
  pool: 5
  username: postgres
  port: 5432

production:
  adapter: postgresql
  database: todo_production
  encoding: utf8
  host: localhost
  password: a
  pool: 5
  username: postgres
  port: 5432